# version: '3'

# services:
#   web:
#     build: .
#     ports:
#       - "5173:80"
#     container_name: youtube-nginx
#     restart: always

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-proxy2
    ports:
      - "8888:80"
    networks:
      - dweb-network
networks:
  dweb-network:
    driver: bridge